name: NestJS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    check:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          issues: write
        steps:
            - uses: actions/checkout@v4
              name: Use Node.js
            
            - uses: kir-dev/automations/actions/node-ci@node-ci
              with:
                node-version: 20
                package-manager: npm
                test-script: test:cov
                gh-comment-token: ${{ secrets.GITHUB_TOKEN }}
                build-artifacts-path: dist
                test-coverage-path: coverage
                
            