name: Production workflow

on:
  push:
    tags: 
      - production
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  publish-prod:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Hello world action
        run: echo "Hello world"