name: Production workflow

on:
  push:
    tags: 
      - production
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  publish-prod:

    uses: kir-dev/workflows/.github/workflows/docker-publish.yml@feat/git-ref
    with:
      ref: production
      docker-tag-config: type=raw,value=latest