name: Production workflow

on:
  workflow_dispatch:
  workflow_run: 
    workflows:
      - "Release workflow"
    types:
      - completed
    branches: 
      - main
  schedule:
    - cron: '*/15 * * * *'

jobs:
  publish-prod:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    uses: kir-dev/workflows/.github/workflows/docker-publish.yml@a62cea224f0fb5bfbf7dcf2406c08c46ce7469bf
    with:
      ref: refs/tags/production
      docker-tag-config: |
        type=raw,value=latest
        type=raw,value=stable,enable=${{ github.event_name == 'workflow_run' }}
