name: Production workflow

on:
  workflow_run: 
    workflows: ["Release workflow"]
    types:
      - completed
    branches: 
      - main
  schedule:
    - cron: '*/15 * * * *'

jobs:
  publish-prod:

    uses: kir-dev/workflows/.github/workflows/docker-publish.yml@main
    with:
      docker-tag-config: type=raw,value=latest
