name: Production workflow for tags

on:
  push:
    tags:
      - 'v*'

jobs:
  docker-publish:
    uses: kir-dev/workflows/.github/workflows/docker-publish.yml@main
    with:
      docker-tag-config: type=raw,value=${{ github.ref_name }}