name: Production workflow

on:
  workflow_run: 
    workflows:
      - "Release workflow"
    types:
      - completed
    branches: 
      - main
  schedule:
    - cron: '*/15 * * * *'

jobs:
  publish-prod:

    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout the production tag
        uses: actions/checkout@v4
        with:
          ref: refs/tags/production
          fetch-tags: true
      
      - name: Deploy to production
        run: |
          echo "Deploying to production"
          git describe
          git status
          git checkout refs/tags/production
          git describe
          git status
          docker build -t ghcr.io/${{ github.repository }}:latest .
          docker push ghcr.io/${{ github.repository }}:latest
          echo "Done"